// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/purchase-tracker-variants/ArcticLight.tsx": () => import("../components/mockups/purchase-tracker-variants/ArcticLight.tsx"),
  "./components/mockups/purchase-tracker-variants/DeepOcean.tsx": () => import("../components/mockups/purchase-tracker-variants/DeepOcean.tsx"),
  "./components/mockups/purchase-tracker-variants/MidnightPro.tsx": () => import("../components/mockups/purchase-tracker-variants/MidnightPro.tsx")
};
